all:
  hosts: {}
  vars:
    zuul:
      _inheritance_path:
      - '<Job base branches: None source: thirdparty-ci-config/zuul.d/jobs.yaml@master#2>'
      - '<Job pure-ci-buildset-reporter branches: None source: thirdparty-ci-config/zuul.d/jobs.yaml@master#33>'
      - '<Job pure-ci-buildset-reporter branches: None source: thirdparty-ci-config/zuul.d/project.yaml@master#20>'
      ansible_version: '8'
      artifacts:
      - branch: master
        change: '920875'
        job: pure-devstack-cinder-tempest-iscsi-aio-noble
        metadata:
          type: zuul_manifest
        name: Zuul Manifest
        patchset: '17'
        project: openstack/cinder
        url: https://github.com/Everpure-Zuul-CI/Cinder-CI/tree/gh-pages/5f1bdf4095ab4066a935e2c2340067bd/pure-devstack-cinder-tempest-iscsi-aio-noble/f142c62d6f394791a197bf0402630de1/zuul-manifest.json
      - branch: master
        change: '920875'
        job: pure-devstack-cinder-tempest-iscsi-aio-noble
        metadata:
          type: unit_test_report
        name: Unit Test Report
        patchset: '17'
        project: openstack/cinder
        url: https://github.com/Everpure-Zuul-CI/Cinder-CI/tree/gh-pages/5f1bdf4095ab4066a935e2c2340067bd/pure-devstack-cinder-tempest-iscsi-aio-noble/f142c62d6f394791a197bf0402630de1/testr_results.html
      - branch: master
        change: '920875'
        job: pure-devstack-cinder-tempest-fc-aio-noble
        metadata:
          type: zuul_manifest
        name: Zuul Manifest
        patchset: '17'
        project: openstack/cinder
        url: https://github.com/Everpure-Zuul-CI/Cinder-CI/tree/gh-pages/5f1bdf4095ab4066a935e2c2340067bd/pure-devstack-cinder-tempest-fc-aio-noble/668676b6bd4d4f22b9fb77297b230c17/zuul-manifest.json
      - branch: master
        change: '920875'
        job: pure-devstack-cinder-tempest-fc-aio-noble
        metadata:
          type: unit_test_report
        name: Unit Test Report
        patchset: '17'
        project: openstack/cinder
        url: https://github.com/Everpure-Zuul-CI/Cinder-CI/tree/gh-pages/5f1bdf4095ab4066a935e2c2340067bd/pure-devstack-cinder-tempest-fc-aio-noble/668676b6bd4d4f22b9fb77297b230c17/testr_results.html
      - branch: master
        change: '920875'
        job: pure-devstack-cinder-tempest-nvme-roce-aio-noble
        metadata:
          type: zuul_manifest
        name: Zuul Manifest
        patchset: '17'
        project: openstack/cinder
        url: https://github.com/Everpure-Zuul-CI/Cinder-CI/tree/gh-pages/5f1bdf4095ab4066a935e2c2340067bd/pure-devstack-cinder-tempest-nvme-roce-aio-noble/f5d9f9d617664e66b0e59ad32bb93bf8/zuul-manifest.json
      - branch: master
        change: '920875'
        job: pure-devstack-cinder-tempest-nvme-roce-aio-noble
        metadata:
          type: unit_test_report
        name: Unit Test Report
        patchset: '17'
        project: openstack/cinder
        url: https://github.com/Everpure-Zuul-CI/Cinder-CI/tree/gh-pages/5f1bdf4095ab4066a935e2c2340067bd/pure-devstack-cinder-tempest-nvme-roce-aio-noble/f5d9f9d617664e66b0e59ad32bb93bf8/testr_results.html
      - branch: master
        change: '920875'
        job: pure-devstack-cinder-tempest-nvme-tcp-aio-noble
        metadata:
          type: zuul_manifest
        name: Zuul Manifest
        patchset: '17'
        project: openstack/cinder
        url: https://github.com/Everpure-Zuul-CI/Cinder-CI/tree/gh-pages/5f1bdf4095ab4066a935e2c2340067bd/pure-devstack-cinder-tempest-nvme-tcp-aio-noble/aa4948058afd43c99fd333985a69f9f4/zuul-manifest.json
      - branch: master
        change: '920875'
        job: pure-devstack-cinder-tempest-nvme-tcp-aio-noble
        metadata:
          type: unit_test_report
        name: Unit Test Report
        patchset: '17'
        project: openstack/cinder
        url: https://github.com/Everpure-Zuul-CI/Cinder-CI/tree/gh-pages/5f1bdf4095ab4066a935e2c2340067bd/pure-devstack-cinder-tempest-nvme-tcp-aio-noble/aa4948058afd43c99fd333985a69f9f4/testr_results.html
      attempts: 1
      branch: master
      build: e473719ca9d6419a9a79ef470636b9f7
      buildset: 5f1bdf4095ab4066a935e2c2340067bd
      change: '920875'
      change_message: 'Report provisioning in driver stats for Quobyte driver


        Fixes driver stats reporting thin/thick provisioning for the

        Quobyte driver along with corresponding tests. Previously only

        the parent class remotefs based stats were reported.


        Implements: blueprint qb-thinprov

        Signed-off-by: Silvan Kaiser <silvan@quobyte.com>

        Change-Id: Ifb619464eac0ffedec9627b29a0da86f3158d228

        '
      change_url: https://review.opendev.org/c/openstack/cinder/+/920875
      child_jobs: []
      commit_id: 7895fffba0ae204d147b8827c93ef76b6cbfc536
      event_id: 1c7e0f09206f42f2a7f99e506dcb12c6
      executor:
        hostname: managesf.cinderci-sf.dev.purestorage.com
        inventory_file: /var/lib/zuul/builds/e473719ca9d6419a9a79ef470636b9f7/ansible/inventory.yaml
        log_root: /var/lib/zuul/builds/e473719ca9d6419a9a79ef470636b9f7/work/logs
        result_data_file: /var/lib/zuul/builds/e473719ca9d6419a9a79ef470636b9f7/work/results.json
        src_root: /var/lib/zuul/builds/e473719ca9d6419a9a79ef470636b9f7/work/src
        work_root: /var/lib/zuul/builds/e473719ca9d6419a9a79ef470636b9f7/work
      items:
      - branch: master
        change: '922082'
        change_url: https://review.opendev.org/c/openstack/cinder/+/922082
        patchset: '12'
        project:
          canonical_hostname: opendev.org
          canonical_name: opendev.org/openstack/cinder
          name: openstack/cinder
          short_name: cinder
          src_dir: src/opendev.org/openstack/cinder
      - branch: master
        change: '920875'
        change_url: https://review.opendev.org/c/openstack/cinder/+/920875
        patchset: '17'
        project:
          canonical_hostname: opendev.org
          canonical_name: opendev.org/openstack/cinder
          name: openstack/cinder
          short_name: cinder
          src_dir: src/opendev.org/openstack/cinder
      job: pure-ci-buildset-reporter
      jobtags: []
      max_attempts: 3
      message: UmVwb3J0IHByb3Zpc2lvbmluZyBpbiBkcml2ZXIgc3RhdHMgZm9yIFF1b2J5dGUgZHJpdmVyCgpGaXhlcyBkcml2ZXIgc3RhdHMgcmVwb3J0aW5nIHRoaW4vdGhpY2sgcHJvdmlzaW9uaW5nIGZvciB0aGUKUXVvYnl0ZSBkcml2ZXIgYWxvbmcgd2l0aCBjb3JyZXNwb25kaW5nIHRlc3RzLiBQcmV2aW91c2x5IG9ubHkKdGhlIHBhcmVudCBjbGFzcyByZW1vdGVmcyBiYXNlZCBzdGF0cyB3ZXJlIHJlcG9ydGVkLgoKSW1wbGVtZW50czogYmx1ZXByaW50IHFiLXRoaW5wcm92ClNpZ25lZC1vZmYtYnk6IFNpbHZhbiBLYWlzZXIgPHNpbHZhbkBxdW9ieXRlLmNvbT4KQ2hhbmdlLUlkOiBJZmI2MTk0NjRlYWMwZmZlZGVjOTYyN2IyOWEwZGE4NmYzMTU4ZDIyOAo=
      patchset: '17'
      pipeline: thirdparty-check
      playbook_context:
        playbook_projects:
          trusted/project_0/cinderci-sf.dev.purestorage.com/thirdparty-ci-config:
            canonical_name: cinderci-sf.dev.purestorage.com/thirdparty-ci-config
            checkout: master
            commit: c7888375825cb3c28bb4e41ddfb1f80c96dc4482
          trusted/project_1/opendev.org/zuul/zuul-jobs:
            canonical_name: opendev.org/zuul/zuul-jobs
            checkout: master
            commit: d2ea119f1a11cb5176f19cb4e2729190b4000e37
        playbooks:
        - path: trusted/project_0/cinderci-sf.dev.purestorage.com/thirdparty-ci-config/playbooks/base/report-buildset.yaml
          roles:
          - checkout: master
            checkout_description: playbook branch
            link_name: ansible/playbook_0/role_0/thirdparty-ci-config
            link_target: trusted/project_0/cinderci-sf.dev.purestorage.com/thirdparty-ci-config
            role_path: ansible/playbook_0/role_0/thirdparty-ci-config/roles
          - checkout: master
            checkout_description: zuul branch
            link_name: ansible/playbook_0/role_1/zuul-jobs
            link_target: trusted/project_1/opendev.org/zuul/zuul-jobs
            role_path: ansible/playbook_0/role_1/zuul-jobs/roles
      post_review: false
      project:
        canonical_hostname: opendev.org
        canonical_name: opendev.org/openstack/cinder
        name: openstack/cinder
        short_name: cinder
        src_dir: src/opendev.org/openstack/cinder
      projects:
        opendev.org/openstack/cinder:
          canonical_hostname: opendev.org
          canonical_name: opendev.org/openstack/cinder
          checkout: master
          checkout_description: zuul branch
          commit: e2164542b0c7bf2542a0de275be00e33a4187e17
          name: openstack/cinder
          required: false
          short_name: cinder
          src_dir: src/opendev.org/openstack/cinder
      ref: refs/changes/75/920875/17
      resources: {}
      tenant: third-party-ci
      timeout: 1800
      voting: false
    zuul_use_fetch_output: true
