all:
  hosts: {}
  vars:
    zuul:
      _inheritance_path:
      - '<Job base branches: None source: thirdparty-ci-config/zuul.d/jobs.yaml@master#2>'
      - '<Job pure-ci-buildset-reporter branches: None source: thirdparty-ci-config/zuul.d/jobs.yaml@master#33>'
      - '<Job pure-ci-buildset-reporter branches: None source: thirdparty-ci-config/zuul.d/project.yaml@master#20>'
      ansible_version: '8'
      artifacts:
      - branch: master
        change: '988742'
        job: pure-devstack-cinder-tempest-iscsi-aio-noble
        metadata:
          type: zuul_manifest
        name: Zuul Manifest
        patchset: '2'
        project: openstack/cinder
        url: https://github.com/Everpure-Zuul-CI/Cinder-CI/tree/gh-pages/a0cfeb8423914727abbc079f2b73e502/pure-devstack-cinder-tempest-iscsi-aio-noble/3c0cd1340aa542ea9f4988b105c8908b/zuul-manifest.json
      - branch: master
        change: '988742'
        job: pure-devstack-cinder-tempest-iscsi-aio-noble
        metadata:
          type: unit_test_report
        name: Unit Test Report
        patchset: '2'
        project: openstack/cinder
        url: https://github.com/Everpure-Zuul-CI/Cinder-CI/tree/gh-pages/a0cfeb8423914727abbc079f2b73e502/pure-devstack-cinder-tempest-iscsi-aio-noble/3c0cd1340aa542ea9f4988b105c8908b/testr_results.html
      - branch: master
        change: '988742'
        job: pure-devstack-cinder-tempest-fc-aio-noble
        metadata:
          type: zuul_manifest
        name: Zuul Manifest
        patchset: '2'
        project: openstack/cinder
        url: https://github.com/Everpure-Zuul-CI/Cinder-CI/tree/gh-pages/a0cfeb8423914727abbc079f2b73e502/pure-devstack-cinder-tempest-fc-aio-noble/3f7571975142493fba95beec62b93af6/zuul-manifest.json
      - branch: master
        change: '988742'
        job: pure-devstack-cinder-tempest-fc-aio-noble
        metadata:
          type: unit_test_report
        name: Unit Test Report
        patchset: '2'
        project: openstack/cinder
        url: https://github.com/Everpure-Zuul-CI/Cinder-CI/tree/gh-pages/a0cfeb8423914727abbc079f2b73e502/pure-devstack-cinder-tempest-fc-aio-noble/3f7571975142493fba95beec62b93af6/testr_results.html
      - branch: master
        change: '988742'
        job: pure-devstack-cinder-tempest-nvme-roce-aio-noble
        metadata:
          type: zuul_manifest
        name: Zuul Manifest
        patchset: '2'
        project: openstack/cinder
        url: https://github.com/Everpure-Zuul-CI/Cinder-CI/tree/gh-pages/a0cfeb8423914727abbc079f2b73e502/pure-devstack-cinder-tempest-nvme-roce-aio-noble/23e17d71878240f5b6a3ffd8e6fb65ae/zuul-manifest.json
      - branch: master
        change: '988742'
        job: pure-devstack-cinder-tempest-nvme-roce-aio-noble
        metadata:
          type: unit_test_report
        name: Unit Test Report
        patchset: '2'
        project: openstack/cinder
        url: https://github.com/Everpure-Zuul-CI/Cinder-CI/tree/gh-pages/a0cfeb8423914727abbc079f2b73e502/pure-devstack-cinder-tempest-nvme-roce-aio-noble/23e17d71878240f5b6a3ffd8e6fb65ae/testr_results.html
      - branch: master
        change: '988742'
        job: pure-devstack-cinder-tempest-nvme-tcp-aio-noble
        metadata:
          type: zuul_manifest
        name: Zuul Manifest
        patchset: '2'
        project: openstack/cinder
        url: https://github.com/Everpure-Zuul-CI/Cinder-CI/tree/gh-pages/a0cfeb8423914727abbc079f2b73e502/pure-devstack-cinder-tempest-nvme-tcp-aio-noble/b995318a988647d7af8fb31cc57a0a2c/zuul-manifest.json
      - branch: master
        change: '988742'
        job: pure-devstack-cinder-tempest-nvme-tcp-aio-noble
        metadata:
          type: unit_test_report
        name: Unit Test Report
        patchset: '2'
        project: openstack/cinder
        url: https://github.com/Everpure-Zuul-CI/Cinder-CI/tree/gh-pages/a0cfeb8423914727abbc079f2b73e502/pure-devstack-cinder-tempest-nvme-tcp-aio-noble/b995318a988647d7af8fb31cc57a0a2c/testr_results.html
      attempts: 1
      branch: master
      build: 5bab3c34da304ad198285babf60ed805
      buildset: a0cfeb8423914727abbc079f2b73e502
      change: '988742'
      change_message: 'Dell PowerFlex: Handle missing errorCode in NVMe-oF REST error
        responses


        Remove redundant "errorCode" in response checks from query_system_nqn,

        query_sdts, query_hosts, and create_nvme_host methods. This ensures

        errors are properly raised even when the response does not contain an

        errorCode field, making error handling more robust.


        Follow up to https://review.opendev.org/c/openstack/cinder/+/912058


        Change-Id: I151ebb3e74826cc65829a12599ec00e0bb808168

        Signed-off-by: Nilesh Thathagar <nilesh.thathagar@dell.com>

        '
      change_url: https://review.opendev.org/c/openstack/cinder/+/988742
      child_jobs: []
      commit_id: d25f41ff8ad74d00f2c8b1d4370cd5363a2715b5
      event_id: c4d108d281ae48898c5cfde2883038f2
      executor:
        hostname: managesf.cinderci-sf.dev.purestorage.com
        inventory_file: /var/lib/zuul/builds/5bab3c34da304ad198285babf60ed805/ansible/inventory.yaml
        log_root: /var/lib/zuul/builds/5bab3c34da304ad198285babf60ed805/work/logs
        result_data_file: /var/lib/zuul/builds/5bab3c34da304ad198285babf60ed805/work/results.json
        src_root: /var/lib/zuul/builds/5bab3c34da304ad198285babf60ed805/work/src
        work_root: /var/lib/zuul/builds/5bab3c34da304ad198285babf60ed805/work
      items:
      - branch: master
        change: '988742'
        change_url: https://review.opendev.org/c/openstack/cinder/+/988742
        patchset: '2'
        project:
          canonical_hostname: opendev.org
          canonical_name: opendev.org/openstack/cinder
          name: openstack/cinder
          short_name: cinder
          src_dir: src/opendev.org/openstack/cinder
      job: pure-ci-buildset-reporter
      jobtags: []
      max_attempts: 3
      message: RGVsbCBQb3dlckZsZXg6IEhhbmRsZSBtaXNzaW5nIGVycm9yQ29kZSBpbiBOVk1lLW9GIFJFU1QgZXJyb3IgcmVzcG9uc2VzCgpSZW1vdmUgcmVkdW5kYW50ICJlcnJvckNvZGUiIGluIHJlc3BvbnNlIGNoZWNrcyBmcm9tIHF1ZXJ5X3N5c3RlbV9ucW4sCnF1ZXJ5X3NkdHMsIHF1ZXJ5X2hvc3RzLCBhbmQgY3JlYXRlX252bWVfaG9zdCBtZXRob2RzLiBUaGlzIGVuc3VyZXMKZXJyb3JzIGFyZSBwcm9wZXJseSByYWlzZWQgZXZlbiB3aGVuIHRoZSByZXNwb25zZSBkb2VzIG5vdCBjb250YWluIGFuCmVycm9yQ29kZSBmaWVsZCwgbWFraW5nIGVycm9yIGhhbmRsaW5nIG1vcmUgcm9idXN0LgoKRm9sbG93IHVwIHRvIGh0dHBzOi8vcmV2aWV3Lm9wZW5kZXYub3JnL2Mvb3BlbnN0YWNrL2NpbmRlci8rLzkxMjA1OAoKQ2hhbmdlLUlkOiBJMTUxZWJiM2U3NDgyNmNjNjU4MjlhMTI1OTllYzAwZTBiYjgwODE2OApTaWduZWQtb2ZmLWJ5OiBOaWxlc2ggVGhhdGhhZ2FyIDxuaWxlc2gudGhhdGhhZ2FyQGRlbGwuY29tPgo=
      patchset: '2'
      pipeline: thirdparty-check
      playbook_context:
        playbook_projects:
          trusted/project_0/cinderci-sf.dev.purestorage.com/thirdparty-ci-config:
            canonical_name: cinderci-sf.dev.purestorage.com/thirdparty-ci-config
            checkout: master
            commit: c7888375825cb3c28bb4e41ddfb1f80c96dc4482
          trusted/project_1/opendev.org/zuul/zuul-jobs:
            canonical_name: opendev.org/zuul/zuul-jobs
            checkout: master
            commit: d2ea119f1a11cb5176f19cb4e2729190b4000e37
        playbooks:
        - path: trusted/project_0/cinderci-sf.dev.purestorage.com/thirdparty-ci-config/playbooks/base/report-buildset.yaml
          roles:
          - checkout: master
            checkout_description: playbook branch
            link_name: ansible/playbook_0/role_0/thirdparty-ci-config
            link_target: trusted/project_0/cinderci-sf.dev.purestorage.com/thirdparty-ci-config
            role_path: ansible/playbook_0/role_0/thirdparty-ci-config/roles
          - checkout: master
            checkout_description: zuul branch
            link_name: ansible/playbook_0/role_1/zuul-jobs
            link_target: trusted/project_1/opendev.org/zuul/zuul-jobs
            role_path: ansible/playbook_0/role_1/zuul-jobs/roles
      post_review: false
      project:
        canonical_hostname: opendev.org
        canonical_name: opendev.org/openstack/cinder
        name: openstack/cinder
        short_name: cinder
        src_dir: src/opendev.org/openstack/cinder
      projects:
        opendev.org/openstack/cinder:
          canonical_hostname: opendev.org
          canonical_name: opendev.org/openstack/cinder
          checkout: master
          checkout_description: zuul branch
          commit: d25f41ff8ad74d00f2c8b1d4370cd5363a2715b5
          name: openstack/cinder
          required: false
          short_name: cinder
          src_dir: src/opendev.org/openstack/cinder
      ref: refs/changes/42/988742/2
      resources: {}
      tenant: third-party-ci
      timeout: 1800
      voting: false
    zuul_use_fetch_output: true
