all:
  hosts: {}
  vars:
    zuul:
      _inheritance_path:
      - '<Job base branches: None source: thirdparty-ci-config/zuul.d/jobs.yaml@master#2>'
      - '<Job pure-ci-buildset-reporter branches: None source: thirdparty-ci-config/zuul.d/jobs.yaml@master#33>'
      - '<Job pure-ci-buildset-reporter branches: None source: thirdparty-ci-config/zuul.d/project.yaml@master#20>'
      ansible_version: '8'
      artifacts:
      - branch: master
        change: '928781'
        job: pure-devstack-cinder-tempest-iscsi-aio-noble
        metadata:
          type: zuul_manifest
        name: Zuul Manifest
        patchset: '18'
        project: openstack/cinder
        url: https://github.com/Everpure-Zuul-CI/Cinder-CI/tree/gh-pages/42dc6b9fb30f466f8172793a826d1f0c/pure-devstack-cinder-tempest-iscsi-aio-noble/c5d8303195d144dd84cc32eaf00a8b95/zuul-manifest.json
      - branch: master
        change: '928781'
        job: pure-devstack-cinder-tempest-iscsi-aio-noble
        metadata:
          type: unit_test_report
        name: Unit Test Report
        patchset: '18'
        project: openstack/cinder
        url: https://github.com/Everpure-Zuul-CI/Cinder-CI/tree/gh-pages/42dc6b9fb30f466f8172793a826d1f0c/pure-devstack-cinder-tempest-iscsi-aio-noble/c5d8303195d144dd84cc32eaf00a8b95/testr_results.html
      - branch: master
        change: '928781'
        job: pure-devstack-cinder-tempest-fc-aio-noble
        metadata:
          type: zuul_manifest
        name: Zuul Manifest
        patchset: '18'
        project: openstack/cinder
        url: https://github.com/Everpure-Zuul-CI/Cinder-CI/tree/gh-pages/42dc6b9fb30f466f8172793a826d1f0c/pure-devstack-cinder-tempest-fc-aio-noble/81797a05699847c0995e09ab20a3d20d/zuul-manifest.json
      - branch: master
        change: '928781'
        job: pure-devstack-cinder-tempest-fc-aio-noble
        metadata:
          type: unit_test_report
        name: Unit Test Report
        patchset: '18'
        project: openstack/cinder
        url: https://github.com/Everpure-Zuul-CI/Cinder-CI/tree/gh-pages/42dc6b9fb30f466f8172793a826d1f0c/pure-devstack-cinder-tempest-fc-aio-noble/81797a05699847c0995e09ab20a3d20d/testr_results.html
      - branch: master
        change: '928781'
        job: pure-devstack-cinder-tempest-nvme-roce-aio-noble
        metadata:
          type: zuul_manifest
        name: Zuul Manifest
        patchset: '18'
        project: openstack/cinder
        url: https://github.com/Everpure-Zuul-CI/Cinder-CI/tree/gh-pages/42dc6b9fb30f466f8172793a826d1f0c/pure-devstack-cinder-tempest-nvme-roce-aio-noble/ce2aa5f709a34c4a812862016f2ffb47/zuul-manifest.json
      - branch: master
        change: '928781'
        job: pure-devstack-cinder-tempest-nvme-roce-aio-noble
        metadata:
          type: unit_test_report
        name: Unit Test Report
        patchset: '18'
        project: openstack/cinder
        url: https://github.com/Everpure-Zuul-CI/Cinder-CI/tree/gh-pages/42dc6b9fb30f466f8172793a826d1f0c/pure-devstack-cinder-tempest-nvme-roce-aio-noble/ce2aa5f709a34c4a812862016f2ffb47/testr_results.html
      - branch: master
        change: '928781'
        job: pure-devstack-cinder-tempest-nvme-tcp-aio-noble
        metadata:
          type: zuul_manifest
        name: Zuul Manifest
        patchset: '18'
        project: openstack/cinder
        url: https://github.com/Everpure-Zuul-CI/Cinder-CI/tree/gh-pages/42dc6b9fb30f466f8172793a826d1f0c/pure-devstack-cinder-tempest-nvme-tcp-aio-noble/d164fdec5bc24c85a14bd5941431caff/zuul-manifest.json
      - branch: master
        change: '928781'
        job: pure-devstack-cinder-tempest-nvme-tcp-aio-noble
        metadata:
          type: unit_test_report
        name: Unit Test Report
        patchset: '18'
        project: openstack/cinder
        url: https://github.com/Everpure-Zuul-CI/Cinder-CI/tree/gh-pages/42dc6b9fb30f466f8172793a826d1f0c/pure-devstack-cinder-tempest-nvme-tcp-aio-noble/d164fdec5bc24c85a14bd5941431caff/testr_results.html
      attempts: 1
      branch: master
      build: d3c27bb55a3f4de28ee34c2a652bb566
      buildset: 42dc6b9fb30f466f8172793a826d1f0c
      change: '928781'
      change_message: 'Pass volume summary filters from API to DB layer


        The volume summary API accepts volume filters but they

        are not applied when calling down to the database layer.


        This fixes that bug by passing the filters to the database

        function in a new microversion.


        This also fixes the bug where we would throw a 500 instead

        of 400 error when passing invalid parameters, this is done

        regardless of microversion.


        Depends-On: https://review.opendev.org/c/openstack/openstacksdk/+/928867

        Closes-Bug: #2080228

        Change-Id: I9efee1a14d670c193768ffef67b1b24e635a6d86

        Signed-off-by: Tobias Urdin <tobias.urdin@binero.com>

        '
      change_url: https://review.opendev.org/c/openstack/cinder/+/928781
      child_jobs: []
      commit_id: 33cac3fc63f7ae5a94345f16bb4b6a17cc803a6e
      event_id: bad364d472834804b19ad87cac398872
      executor:
        hostname: managesf.cinderci-sf.dev.purestorage.com
        inventory_file: /var/lib/zuul/builds/d3c27bb55a3f4de28ee34c2a652bb566/ansible/inventory.yaml
        log_root: /var/lib/zuul/builds/d3c27bb55a3f4de28ee34c2a652bb566/work/logs
        result_data_file: /var/lib/zuul/builds/d3c27bb55a3f4de28ee34c2a652bb566/work/results.json
        src_root: /var/lib/zuul/builds/d3c27bb55a3f4de28ee34c2a652bb566/work/src
        work_root: /var/lib/zuul/builds/d3c27bb55a3f4de28ee34c2a652bb566/work
      items:
      - branch: master
        change: '928846'
        change_url: https://review.opendev.org/c/openstack/cinder/+/928846
        patchset: '18'
        project:
          canonical_hostname: opendev.org
          canonical_name: opendev.org/openstack/cinder
          name: openstack/cinder
          short_name: cinder
          src_dir: src/opendev.org/openstack/cinder
      - branch: master
        change: '928781'
        change_url: https://review.opendev.org/c/openstack/cinder/+/928781
        patchset: '18'
        project:
          canonical_hostname: opendev.org
          canonical_name: opendev.org/openstack/cinder
          name: openstack/cinder
          short_name: cinder
          src_dir: src/opendev.org/openstack/cinder
      job: pure-ci-buildset-reporter
      jobtags: []
      max_attempts: 3
      message: UGFzcyB2b2x1bWUgc3VtbWFyeSBmaWx0ZXJzIGZyb20gQVBJIHRvIERCIGxheWVyCgpUaGUgdm9sdW1lIHN1bW1hcnkgQVBJIGFjY2VwdHMgdm9sdW1lIGZpbHRlcnMgYnV0IHRoZXkKYXJlIG5vdCBhcHBsaWVkIHdoZW4gY2FsbGluZyBkb3duIHRvIHRoZSBkYXRhYmFzZSBsYXllci4KClRoaXMgZml4ZXMgdGhhdCBidWcgYnkgcGFzc2luZyB0aGUgZmlsdGVycyB0byB0aGUgZGF0YWJhc2UKZnVuY3Rpb24gaW4gYSBuZXcgbWljcm92ZXJzaW9uLgoKVGhpcyBhbHNvIGZpeGVzIHRoZSBidWcgd2hlcmUgd2Ugd291bGQgdGhyb3cgYSA1MDAgaW5zdGVhZApvZiA0MDAgZXJyb3Igd2hlbiBwYXNzaW5nIGludmFsaWQgcGFyYW1ldGVycywgdGhpcyBpcyBkb25lCnJlZ2FyZGxlc3Mgb2YgbWljcm92ZXJzaW9uLgoKRGVwZW5kcy1PbjogaHR0cHM6Ly9yZXZpZXcub3BlbmRldi5vcmcvYy9vcGVuc3RhY2svb3BlbnN0YWNrc2RrLysvOTI4ODY3CkNsb3Nlcy1CdWc6ICMyMDgwMjI4CkNoYW5nZS1JZDogSTllZmVlMWExNGQ2NzBjMTkzNzY4ZmZlZjY3YjFiMjRlNjM1YTZkODYKU2lnbmVkLW9mZi1ieTogVG9iaWFzIFVyZGluIDx0b2JpYXMudXJkaW5AYmluZXJvLmNvbT4K
      patchset: '18'
      pipeline: thirdparty-check
      playbook_context:
        playbook_projects:
          trusted/project_0/cinderci-sf.dev.purestorage.com/thirdparty-ci-config:
            canonical_name: cinderci-sf.dev.purestorage.com/thirdparty-ci-config
            checkout: master
            commit: c7888375825cb3c28bb4e41ddfb1f80c96dc4482
          trusted/project_1/opendev.org/zuul/zuul-jobs:
            canonical_name: opendev.org/zuul/zuul-jobs
            checkout: master
            commit: d2ea119f1a11cb5176f19cb4e2729190b4000e37
        playbooks:
        - path: trusted/project_0/cinderci-sf.dev.purestorage.com/thirdparty-ci-config/playbooks/base/report-buildset.yaml
          roles:
          - checkout: master
            checkout_description: playbook branch
            link_name: ansible/playbook_0/role_0/thirdparty-ci-config
            link_target: trusted/project_0/cinderci-sf.dev.purestorage.com/thirdparty-ci-config
            role_path: ansible/playbook_0/role_0/thirdparty-ci-config/roles
          - checkout: master
            checkout_description: zuul branch
            link_name: ansible/playbook_0/role_1/zuul-jobs
            link_target: trusted/project_1/opendev.org/zuul/zuul-jobs
            role_path: ansible/playbook_0/role_1/zuul-jobs/roles
      post_review: false
      project:
        canonical_hostname: opendev.org
        canonical_name: opendev.org/openstack/cinder
        name: openstack/cinder
        short_name: cinder
        src_dir: src/opendev.org/openstack/cinder
      projects:
        opendev.org/openstack/cinder:
          canonical_hostname: opendev.org
          canonical_name: opendev.org/openstack/cinder
          checkout: master
          checkout_description: zuul branch
          commit: 33cac3fc63f7ae5a94345f16bb4b6a17cc803a6e
          name: openstack/cinder
          required: false
          short_name: cinder
          src_dir: src/opendev.org/openstack/cinder
      ref: refs/changes/81/928781/18
      resources: {}
      tenant: third-party-ci
      timeout: 1800
      voting: false
    zuul_use_fetch_output: true
